03 mongodb
hellene-mary/nodejs-homework-rest-api pull request #2
Opened 2023-01-15 19:23 UTC by hellene-mary

2023-01-15 21:29 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-15 21:29 UTC, KhYulian commented on app.js
> +  }
Мржна скоротити. Використайте ||

2023-01-15 21:29 UTC, KhYulian commented on controllers/contacts.controller.js
> +  const response = await Contact.findById(contactId)
непотрібно робити окремий запит в БД, Вивчіть результат findByIdAndRemove

2023-01-15 21:29 UTC, KhYulian commented on controllers/contacts.controller.js
> +  }
Непотрібна перевірка. Для валідації полів використовуйте Joi, та middleware

2023-01-15 21:29 UTC, KhYulian commented on helpers/helpers.js
> +module.exports = {
Використовуйте класи https://javascript.info/custom-errors

2023-01-15 21:29 UTC, KhYulian commented on server.js
> +main()
Можна використати IIFE

2023-01-16 10:02 UTC, hellene-mary commented on app.js
> +  }
не зрозуміла, що саме можна скоротити?

2023-01-16 10:03 UTC, hellene-mary commented on server.js
> +main()
можна, але мені більше подобається так. поки що мені iife виглядає важко для читання

2023-01-16 13:11 UTC, KhYulian commented on app.js
> +  }
return res.status(err.status || 500).json(...

2023-01-16 13:12 UTC, KhYulian commented
Усі непотрібні коменти видаляйте

2023-01-16 14:27 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-16 14:28 UTC, merged